version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:master
    ports:
      - "3100:3100"
    volumes:
      - /home/sych/Work/loki_exporter/example:/etc/loki
    command:
      -config.file=/etc/loki/loki.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:master
    volumes:
      - /home/sych/Work/loki_exporter/example:/etc/promtail
      - /var/log:/var/log
    command:
      -config.file=/etc/promtail/promtail.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    environment:
      GF_EXPLORE_ENABLED: "true"
    networks:
      - loki

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/sych/Work/loki_exporter/example:/etc/prometheus
    command:
      --config.file=/etc/prometheus/prometheus.yml
    networks:
      - loki

#   loki_exporter:
#     image: ricoberger/loki_exporter
#     ports:
#       - "9524:9524"
#     volumes:
#       - $PWD:/etc/loki_exporter
#     command:
#       -config.file=/etc/loki_exporter/loki_exporter.yml
#     networks:
#       - loki
