version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:master
    ports:
      - "3100:3100"
    volumes:
      - ./config:/etc/loki
    command:
      -config.file=/etc/loki/loki.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:master
    volumes:
      - ./config:/etc/promtail
      - /var/log:/var/log
    command:
      -config.file=/etc/promtail/promtail.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    environment:
      GF_EXPLORE_ENABLED: "true"
    networks:
      - loki

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
    command:
      --config.file=/etc/prometheus/prometheus.yml
    networks:
      - loki

  python_loki_exporter:
    build:
      context: ../
    ports:
      - "8779:8779"
    volumes:
      - ./config:/etc/loki_exporter
    command:
      python3
      main.py
      -f
      /etc/loki_exporter/exporter_config.json
    networks:
      - loki
