# my global config
global:
  scrape_interval: 60s
  evaluation_interval: 60s
  scrape_timeout: 30s

scrape_configs:
  - job_name: 'varlogs'
    metrics_path: /metrics
    static_configs:
      - targets:
        - python_loki_exporter:8779